#! /bin/zsh
install_package() {
    yes| sudo pacman -S libsodium python-pip> /dev/null
    sudo pip install shadowsocks
    touch ~/.nss_packages_installed
}

[ ! -f ~/.nss_packages_installed ] && echo "installing packages" && install_package

sudo chmod 777 /usr/lib/python3.7/site-packages/shadowsocks/crypto/openssl.py  && sudo python3 $(which archnssfixer) > /dev/null
sudo sslocal -s $1 -p $2 -k $3 -m $4 -b 0.0.0.0 -d start


# goproxy from github: transforming socks5 to http and socks5
sudo nohup proxy sps -S socks -T tcp -P 127.0.0.1:1080 -t tcp -p :1081 -h aes-192-cfb -j pass &
echo ''
